cat_to_db:
  상의: shirt
  아우터: outer
  하의: pant
chroma_db_path: src/data/chroma_db
chromadb_ref_embedding_dir: src/data/chromadb_ref
chromadb_user_war_embedding_dir: src/data/chroma_wardrobe
combination_top_k: 3
folder_map:
  bottoms: 하의
  outers: 아우터
  tops: 상의
  상의: 상의
  아우터: 아우터
  하의: 하의
item_top_k: 3
model_name: patrickjohncyh/fashion-clip
num_of_show: 3
use_fp16: true
user_body_image: data/user_body_image/sample_body.png
user_clothes_dir: data/user_wardrobe_images
user_bottom_image: data/user_wardrobe_images/bottoms
user_outer_image: data/user_wardrobe_images/outers
user_top_image: data/user_wardrobe_images/tops
